networks:
     bridge:
          name: colebot_bridge
          driver: bridge

services:
     bot:
          container_name: colebot
          build:
               context: .
               dockerfile: Dockerfile
          env_file:
               - .env
          networks:
               - bridge
