networks:
    bridge:
        name: bot_bridge
        driver: bridge

services:
    bot:
        container_name: bot
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        networks:
            - bridge
